const DOMAIN = 'NOTIFICATIONS';
export const CONNECT_ACTION = `${DOMAIN}@CONNECT`;
export const RECEIVE_ACTION = `${DOMAIN}@RECEIVE`;

export const TYPE = {
  CONNECTION: 10,
  PING: 20,
  UPDATE_TASK: 30
};